# To execute this docker compose yml file use `docker compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v3.yml down`
services:
  vendor-portal:
    image: kumarlokesh57/selenium
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub
      - THREAD_COUNT=3
      - TEST_SUITE=vendor-portal.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output

  flight-reservation:
    image: kumarlokesh57/selenium
    environment:
      - BROWSER=firefox
      - HUB_HOST=selenium-hub
      - THREAD_COUNT=3
      - TEST_SUITE=flight-reservation.xml
    volumes:
      - ./output/flight-reservation:/home/selenium-docker/test-output